version: "3"

services:
  web:
    container_name: react_crud
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
  
  mongo:
    container_name: mongodatabase
    image: mongo
    ports:
      - "27018:27017"



 